### ISSUE TITLE
Updated for latest Objective-C/iOS

### ISSUE THREAD

**Issue by hemangshah** [aliHafizji/TowerOfHanoi--cocos2d#1]
Hi Ali, are you accepting PR for this project? Yesterday, I downloaded it just as TOH was my favorite game. I have corrected it for modern iOS and the project is compiling in Xcode 9.0 beta. Please let me know and I will make a PR.

**Comment by aliHafizji** [comment]
Hi Hemang.
Sure. Send me the PR I'll go through the code changes and we can merge it.

This was written a long time ago so it might take me sometime to go through everything.

Ali

**Comment by hemangshah** [comment]
No problem! Let me make a PR right away!

**Comment by hemangshah** [comment]
Sent! Kindly review.
